### ISSUE TITLE
Visibility problem of connection indicator

### ISSUE THREAD

**Issue by JunhoeKim** [muclipse/omnitrack_android#26]
When user removes a connection in `AttributeDetailActivity` and saves changes, Change is not immediately applied to connectionIndicatorSubProxy in `TrackerDetailStructureTabFragment`.
I think this problem is occurred by inflated view from ViewStub.

![image](https://user-images.githubusercontent.com/26426778/34349627-8c32bfa8-ea55-11e7-9833-4bf008f7bdde.png)

**Comment by muclipse** [comment]
Fixed in ad8221b573b8c3e7866d886ebdc08f868811be45
